# .github/workflows/build-and-test.yml
name: Build and Test
on:
  push: 
    branches:
      - main
  pull_request:
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm clean-install
      - name: Run the application
        run: nohup npm run start & 
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@1.3.1
        with: 
          apiKey: ${{ secrets.HAWK_API_KEY }}
